### ISSUE TITLE
[BUG] Download does never start

### ISSUE THREAD

**Issue by saschabrockel** [Xoconoch/spotizerr#180]
**Describe the bug**
I can queue whatever I want but nothing will ever start to download. I got the feeling my installation is corrupt because it worked some versions ago and after having a look today into the tool everything was gone. My Spotify and Deezer account and the credentials. Even though the files in my Docker volume were and are still there!

**To Reproduce**
Precise steps to reproduce the behavior (start from how you built your container):
1. Queue anything
2. The download will never start

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**docker-compose.yaml**
```
services:
    spotizerr:
        container_name: spotizerr
        networks:
            - unraid
        environment:
            - TZ=Europe/Berlin
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - REDIS_DB=0
            - REDIS_URL=redis://redis:6379/0
            - REDIS_BACKEND=redis://redis:6379/0
            - EXPLICIT_FILTER=false
            - PUID=99
            - PGID=100
            - UMASK=0022
            - CA_TS_FALLBACK_DIR=/app/data
        ports:
            - 7171:7171/tcp
        volumes:
            - /mnt/cache/appdata/spotizerr:/app/data:rw
            - /mnt/user/downloads/:/app/downloads:rw
            - /mnt/cache/appdata/spotizerr/logs:/app/logs:rw
        image: cooldockerizer93/spotizerr
networks:
    unraid:
        external: true
        name: unraid
```

**.env**
```
Paste it here
```

**Config**
```
{
    "service": "spotify",
    "spotify": "SpotiAccount",
    "deezer": "DeezerAccount",
    "fallback": false,
    "spotifyQuality": "VERY_HIGH",
    "deezerQuality": "MP3_320",
    "realTime": false,
    "customDirFormat": "music",
    "customTrackFormat": "%artist% - %music%",
    "tracknum_padding": true,
    "maxConcurrentDownloads": 3,
    "maxRetries": 3,
    "retryDelaySeconds": 5,
    "retry_delay_increase": 5,
    "explicitFilter": false,
    "downloadQueueVisible": true,
    "save_cover": true,
    "convertTo": "MP3",
    "bitrate": "320k"
}
```

**Logs**
```
Using Redis at redis://redis:6379/0
Using existing group: users (GID: 100)
useradd warning: appuser's uid 99 outside of the UID_MIN 1000 and UID_MAX 60000 range.
Created user: appuser (UID: 99)
Setting permissions for /app directories...
Starting application as appuser...
Redis configuration: REDIS_URL=redis://redis:6379/0, REDIS_BACKEND=redis://redis:6379/0
Playlists database initialized/updated successfully at data/watch/playlists.db
Artists database initialized/updated successfully at data/watch/artists.db
Watch Scheduler: Thread started.
Watch Manager: Background scheduler started (includes playlists and artists).
Playlist Watch Manager initialized and registered for shutdown.
Watch Scheduler: Watch feature is disabled in config. Skipping checks.
Credentials database initialized/schema checked at data/creds/accounts.db
CeleryManager initialized. Download concurrency set to: 3
2025-06-12 04:14:23 [INFO] Logging system initialized
2025-06-12 04:14:23 [INFO] === Spotizerr Application Starting ===
2025-06-12 04:14:23 [INFO] Checking Redis connection to redis:6379
2025-06-12 04:14:23 [INFO] Successfully connected to Redis
2025-06-12 04:14:23 [INFO] Watch Manager: Background scheduler already running.
2025-06-12 04:14:23 [INFO] Starting Celery workers with dynamic configuration
2025-06-12 04:14:23 [INFO] Starting Celery Download Worker with command: celery -A routes.utils.celery_tasks worker --loglevel=INFO -Q downloads -c 3 --hostname=worker_dlw@%h --pool=prefork
2025-06-12 04:14:23 [INFO] Celery Download Worker (PID: 29) started with concurrency 3.
2025-06-12 04:14:23 [INFO] Starting Celery Utility Worker with command: celery -A routes.utils.celery_tasks worker --loglevel=INFO -Q utility_tasks,default -c 3 --hostname=worker_utw@%h --pool=prefork
2025-06-12 04:14:23 [INFO] Celery Utility Worker (PID: 32) started with concurrency 3.
2025-06-12 04:14:23 [INFO] CeleryManager: Config monitor thread active, monitoring configuration changes...
2025-06-12 04:14:23 [INFO] CeleryManager: Config monitor thread started.
2025-06-12 04:14:23 [INFO] Added missing column 'parent_task_id TEXT' to download_history table.
2025-06-12 04:14:23 [INFO] Added missing column 'track_status TEXT' to download_history table.
2025-06-12 04:14:23 [INFO] Added missing column 'summary_json TEXT' to download_history table.
2025-06-12 04:14:23 [INFO] Added missing column 'total_successful INTEGER' to download_history table.
2025-06-12 04:14:23 [INFO] Added missing column 'total_skipped INTEGER' to download_history table.
2025-06-12 04:14:23 [INFO] Added missing column 'total_failed INTEGER' to download_history table.
2025-06-12 04:14:23 [INFO] Download history table schema updated at data/history/download_history.db
2025-06-12 04:14:23 [INFO] Starting Flask server on port 7171
2025-06-12 04:14:23 [INFO] Serving on http://0.0.0.0:7171
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: Redis configuration: REDIS_URL=redis://redis:6379/0, REDIS_BACKEND=redis://redis:6379/0
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: Redis configuration: REDIS_URL=redis://redis:6379/0, REDIS_BACKEND=redis://redis:6379/0
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: Playlists database initialized/updated successfully at data/watch/playlists.db
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: Artists database initialized/updated successfully at data/watch/artists.db
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: Watch Scheduler: Thread started.
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: Watch Manager: Background scheduler started (includes playlists and artists).
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: Playlist Watch Manager initialized and registered for shutdown.
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: Watch Scheduler: Watch feature is disabled in config. Skipping checks.
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: Playlists database initialized/updated successfully at data/watch/playlists.db
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: Artists database initialized/updated successfully at data/watch/artists.db
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: Watch Scheduler: Thread started.
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: Watch Manager: Background scheduler started (includes playlists and artists).
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: Playlist Watch Manager initialized and registered for shutdown.
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: Watch Scheduler: Watch feature is disabled in config. Skipping checks.
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: Celery worker initialized with concurrency 3
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: Worker config: spotifyQuality=VERY_HIGH, deezerQuality=MP3_320
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: Celery worker initialized with concurrency 3
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: Worker config: spotifyQuality=VERY_HIGH, deezerQuality=MP3_320
2025-06-12 04:14:23 [INFO] Celery[UW-STDOUT]: Celery Download Queue Manager initialized with max_concurrent=3
2025-06-12 04:14:23 [INFO] Celery[UW-STDOUT]: 
2025-06-12 04:14:23 [INFO] Celery[UW-STDOUT]: -------------- worker_utw@9d9b4ab79f78 v5.5.3 (immunity)
2025-06-12 04:14:23 [INFO] Celery[UW-STDOUT]: --- ***** -----
2025-06-12 04:14:23 [INFO] Celery[UW-STDOUT]: -- ******* ---- Linux-6.12.24-Unraid-x86_64-with-glibc2.36 2025-06-12 04:14:23
2025-06-12 04:14:23 [INFO] Celery[UW-STDOUT]: - *** --- * ---
2025-06-12 04:14:23 [INFO] Celery[UW-STDOUT]: - ** ---------- [config]
2025-06-12 04:14:23 [INFO] Celery[UW-STDOUT]: - ** ---------- .> app:         routes.utils.celery_tasks:0x14bdb2de9ac0
2025-06-12 04:14:23 [INFO] Celery[UW-STDOUT]: - ** ---------- .> transport:   redis://redis:6379/0
2025-06-12 04:14:23 [INFO] Celery[UW-STDOUT]: - ** ---------- .> results:     redis://redis:6379/0
2025-06-12 04:14:23 [INFO] Celery[UW-STDOUT]: - *** --- * --- .> concurrency: 3 (prefork)
2025-06-12 04:14:23 [INFO] Celery[UW-STDOUT]: -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
2025-06-12 04:14:23 [INFO] Celery[UW-STDOUT]: --- ***** -----
2025-06-12 04:14:23 [INFO] Celery[UW-STDOUT]: -------------- [queues]
2025-06-12 04:14:23 [INFO] Celery[UW-STDOUT]: .> default          exchange=default(direct) key=default
2025-06-12 04:14:23 [INFO] Celery[UW-STDOUT]: .> utility_tasks    exchange=utility_tasks(direct) key=utility_tasks
2025-06-12 04:14:23 [INFO] Celery[UW-STDOUT]: 
2025-06-12 04:14:23 [INFO] Celery[UW-STDOUT]: [tasks]
2025-06-12 04:14:23 [INFO] Celery[UW-STDOUT]: . cleanup_stale_errors
2025-06-12 04:14:23 [INFO] Celery[UW-STDOUT]: . delayed_delete_task_data
2025-06-12 04:14:23 [INFO] Celery[UW-STDOUT]: . download_album
2025-06-12 04:14:23 [INFO] Celery[UW-STDOUT]: . download_playlist
2025-06-12 04:14:23 [INFO] Celery[UW-STDOUT]: . download_track
2025-06-12 04:14:23 [INFO] Celery[UW-STDOUT]: 
2025-06-12 04:14:23 [INFO] Celery[DW-STDOUT]: Celery Download Queue Manager initialized with max_concurrent=3
2025-06-12 04:14:23 [INFO] Celery[DW-STDOUT]: 
2025-06-12 04:14:23 [INFO] Celery[DW-STDOUT]: -------------- worker_dlw@9d9b4ab79f78 v5.5.3 (immunity)
2025-06-12 04:14:23 [INFO] Celery[DW-STDOUT]: --- ***** -----
2025-06-12 04:14:23 [INFO] Celery[DW-STDOUT]: -- ******* ---- Linux-6.12.24-Unraid-x86_64-with-glibc2.36 2025-06-12 04:14:23
2025-06-12 04:14:23 [INFO] Celery[DW-STDOUT]: - *** --- * ---
2025-06-12 04:14:23 [INFO] Celery[DW-STDOUT]: - ** ---------- [config]
2025-06-12 04:14:23 [INFO] Celery[DW-STDOUT]: - ** ---------- .> app:         routes.utils.celery_tasks:0x154305194230
2025-06-12 04:14:23 [INFO] Celery[DW-STDOUT]: - ** ---------- .> transport:   redis://redis:6379/0
2025-06-12 04:14:23 [INFO] Celery[DW-STDOUT]: - ** ---------- .> results:     redis://redis:6379/0
2025-06-12 04:14:23 [INFO] Celery[DW-STDOUT]: - *** --- * --- .> concurrency: 3 (prefork)
2025-06-12 04:14:23 [INFO] Celery[DW-STDOUT]: -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
2025-06-12 04:14:23 [INFO] Celery[DW-STDOUT]: --- ***** -----
2025-06-12 04:14:23 [INFO] Celery[DW-STDOUT]: -------------- [queues]
2025-06-12 04:14:23 [INFO] Celery[DW-STDOUT]: .> downloads        exchange=downloads(direct) key=downloads
2025-06-12 04:14:23 [INFO] Celery[DW-STDOUT]: 
2025-06-12 04:14:23 [INFO] Celery[DW-STDOUT]: 
2025-06-12 04:14:23 [INFO] Celery[DW-STDOUT]: [tasks]
2025-06-12 04:14:23 [INFO] Celery[DW-STDOUT]: . cleanup_stale_errors
2025-06-12 04:14:23 [INFO] Celery[DW-STDOUT]: . delayed_delete_task_data
2025-06-12 04:14:23 [INFO] Celery[DW-STDOUT]: . download_album
2025-06-12 04:14:23 [INFO] Celery[DW-STDOUT]: . download_playlist
2025-06-12 04:14:23 [INFO] Celery[DW-STDOUT]: . download_track
2025-06-12 04:14:23 [INFO] Celery[DW-STDOUT]: 
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: Connected to redis://redis:6379/0
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: Connected to redis://redis:6379/0
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: mingle: searching for neighbors
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: mingle: searching for neighbors
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: Unrecoverable error: ContentDisallowed('Refusing to deserialize untrusted content of type pickle (application/x-python-serialize)')
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: Traceback (most recent call last):
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: File "/usr/local/lib/python3.12/site-packages/celery/worker/worker.py", line 203, in start
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: self.blueprint.start(self)
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: File "/usr/local/lib/python3.12/site-packages/celery/bootsteps.py", line 116, in start
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: step.start(parent)
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: File "/usr/local/lib/python3.12/site-packages/celery/bootsteps.py", line 365, in start
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: return self.obj.start()
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: ^^^^^^^^^^^^^^^^
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 341, in start
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: blueprint.start(self)
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: File "/usr/local/lib/python3.12/site-packages/celery/bootsteps.py", line 116, in start
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: step.start(parent)
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/mingle.py", line 37, in start
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: self.sync(c)
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/mingle.py", line 41, in sync
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: replies = self.send_hello(c)
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: ^^^^^^^^^^^^^^^^^^
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/mingle.py", line 54, in send_hello
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: replies = inspect.hello(c.hostname, our_revoked._data) or {}
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: File "/usr/local/lib/python3.12/site-packages/celery/app/control.py", line 389, in hello
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: return self._request('hello', from_node=from_node, revoked=revoked)
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: File "/usr/local/lib/python3.12/site-packages/celery/app/control.py", line 106, in _request
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: return self._prepare(self.app.control.broadcast(
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: File "/usr/local/lib/python3.12/site-packages/celery/app/control.py", line 777, in broadcast
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: return self.mailbox(conn)._broadcast(
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: File "/usr/local/lib/python3.12/site-packages/kombu/pidbox.py", line 346, in _broadcast
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: return self._collect(reply_ticket, limit=limit,
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: File "/usr/local/lib/python3.12/site-packages/kombu/pidbox.py", line 388, in _collect
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: self.connection.drain_events(timeout=timeout)
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: File "/usr/local/lib/python3.12/site-packages/kombu/connection.py", line 341, in drain_events
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: return self.transport.drain_events(self.connection, **kwargs)
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: File "/usr/local/lib/python3.12/site-packages/kombu/transport/virtual/base.py", line 997, in drain_events
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: get(self._deliver, timeout=timeout)
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: File "/usr/local/lib/python3.12/site-packages/kombu/transport/redis.py", line 598, in get
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: ret = self.handle_event(fileno, event)
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: File "/usr/local/lib/python3.12/site-packages/kombu/transport/redis.py", line 580, in handle_event
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: return self.on_readable(fileno), self
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: ^^^^^^^^^^^^^^^^^^^^^^^^
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: File "/usr/local/lib/python3.12/site-packages/kombu/transport/redis.py", line 576, in on_readable
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: Unrecoverable error: ContentDisallowed('Refusing to deserialize untrusted content of type pickle (application/x-python-serialize)')
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: chan.handlers[type]()
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: Traceback (most recent call last):
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: File "/usr/local/lib/python3.12/site-packages/kombu/transport/redis.py", line 986, in _brpop_read
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: File "/usr/local/lib/python3.12/site-packages/celery/worker/worker.py", line 203, in start
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: self.connection._deliver(loads(bytes_to_str(item)), dest)
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: self.blueprint.start(self)
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: File "/usr/local/lib/python3.12/site-packages/kombu/transport/virtual/base.py", line 1017, in _deliver
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: File "/usr/local/lib/python3.12/site-packages/celery/bootsteps.py", line 116, in start
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: callback(message)
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: step.start(parent)
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: File "/usr/local/lib/python3.12/site-packages/kombu/transport/virtual/base.py", line 639, in _callback
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: File "/usr/local/lib/python3.12/site-packages/celery/bootsteps.py", line 365, in start
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: return callback(message)
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: return self.obj.start()
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: ^^^^^^^^^^^^^^^^^
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: ^^^^^^^^^^^^^^^^
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: File "/usr/local/lib/python3.12/site-packages/kombu/messaging.py", line 662, in _receive_callback
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 341, in start
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: decoded = None if on_m else message.decode()
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: blueprint.start(self)
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: ^^^^^^^^^^^^^^^^
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: File "/usr/local/lib/python3.12/site-packages/celery/bootsteps.py", line 116, in start
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: File "/usr/local/lib/python3.12/site-packages/kombu/message.py", line 201, in decode
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: step.start(parent)
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: self._decoded_cache = self._decode()
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/mingle.py", line 37, in start
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: ^^^^^^^^^^^^^^
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: self.sync(c)
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: File "/usr/local/lib/python3.12/site-packages/kombu/message.py", line 205, in _decode
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/mingle.py", line 41, in sync
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: return loads(self.body, self.content_type,
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: replies = self.send_hello(c)
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: ^^^^^^^^^^^^^^^^^^
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: File "/usr/local/lib/python3.12/site-packages/kombu/serialization.py", line 255, in loads
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/mingle.py", line 54, in send_hello
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: raise self._for_untrusted_content(content_type, 'untrusted')
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: replies = inspect.hello(c.hostname, our_revoked._data) or {}
2025-06-12 04:14:23 [INFO] Celery[DW-STDERR]: kombu.exceptions.ContentDisallowed: Refusing to deserialize untrusted content of type pickle (application/x-python-serialize)
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: File "/usr/local/lib/python3.12/site-packages/celery/app/control.py", line 389, in hello
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: return self._request('hello', from_node=from_node, revoked=revoked)
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: File "/usr/local/lib/python3.12/site-packages/celery/app/control.py", line 106, in _request
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: return self._prepare(self.app.control.broadcast(
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: File "/usr/local/lib/python3.12/site-packages/celery/app/control.py", line 777, in broadcast
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: return self.mailbox(conn)._broadcast(
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: File "/usr/local/lib/python3.12/site-packages/kombu/pidbox.py", line 346, in _broadcast
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: return self._collect(reply_ticket, limit=limit,
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: File "/usr/local/lib/python3.12/site-packages/kombu/pidbox.py", line 388, in _collect
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: self.connection.drain_events(timeout=timeout)
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: File "/usr/local/lib/python3.12/site-packages/kombu/connection.py", line 341, in drain_events
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: return self.transport.drain_events(self.connection, **kwargs)
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: File "/usr/local/lib/python3.12/site-packages/kombu/transport/virtual/base.py", line 997, in drain_events
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: get(self._deliver, timeout=timeout)
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: File "/usr/local/lib/python3.12/site-packages/kombu/transport/redis.py", line 598, in get
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: ret = self.handle_event(fileno, event)
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: File "/usr/local/lib/python3.12/site-packages/kombu/transport/redis.py", line 580, in handle_event
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: return self.on_readable(fileno), self
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: ^^^^^^^^^^^^^^^^^^^^^^^^
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: File "/usr/local/lib/python3.12/site-packages/kombu/transport/redis.py", line 576, in on_readable
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: chan.handlers[type]()
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: File "/usr/local/lib/python3.12/site-packages/kombu/transport/redis.py", line 986, in _brpop_read
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: self.connection._deliver(loads(bytes_to_str(item)), dest)
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: File "/usr/local/lib/python3.12/site-packages/kombu/transport/virtual/base.py", line 1017, in _deliver
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: callback(message)
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: File "/usr/local/lib/python3.12/site-packages/kombu/transport/virtual/base.py", line 639, in _callback
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: return callback(message)
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: ^^^^^^^^^^^^^^^^^
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: File "/usr/local/lib/python3.12/site-packages/kombu/messaging.py", line 662, in _receive_callback
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: decoded = None if on_m else message.decode()
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: ^^^^^^^^^^^^^^^^
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: File "/usr/local/lib/python3.12/site-packages/kombu/message.py", line 201, in decode
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: self._decoded_cache = self._decode()
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: ^^^^^^^^^^^^^^
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: File "/usr/local/lib/python3.12/site-packages/kombu/message.py", line 205, in _decode
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: return loads(self.body, self.content_type,
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: File "/usr/local/lib/python3.12/site-packages/kombu/serialization.py", line 255, in loads
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: raise self._for_untrusted_content(content_type, 'untrusted')
2025-06-12 04:14:23 [INFO] Celery[UW-STDERR]: kombu.exceptions.ContentDisallowed: Refusing to deserialize untrusted content of type pickle (application/x-python-serialize)
2025-06-12 04:14:24 [INFO] Celery[DW-STDERR]: Watch Manager: Stopping background scheduler...
2025-06-12 04:14:24 [INFO] Celery[DW-STDERR]: Watch Scheduler: Thread stopped.
2025-06-12 04:14:24 [INFO] Celery[DW-STDERR]: Watch Manager: Background scheduler stopped.
2025-06-12 04:14:24 [INFO] Celery[UW-STDERR]: Watch Manager: Stopping background scheduler...
2025-06-12 04:14:24 [INFO] Celery[UW-STDERR]: Watch Scheduler: Thread stopped.
2025-06-12 04:14:24 [INFO] Celery[UW-STDERR]: Watch Manager: Background scheduler stopped.
2025-06-12 04:14:25 [INFO] Celery[DW-STDERR] stream reader thread finished.
2025-06-12 04:14:25 [INFO] Celery[DW-STDOUT] stream reader thread finished.
2025-06-12 04:14:25 [INFO] Celery[UW-STDERR] stream reader thread finished.
2025-06-12 04:14:25 [INFO] Celery[UW-STDOUT] stream reader thread finished.
2025-06-12 04:15:19 [INFO] Search requested: query='rammstein', type=track, limit=40, main_account_name=CptDayDreamer
2025-06-12 04:15:19 [WARNING] Couldn't decode JSON from cache at: .cache
2025-06-12 04:15:20 [INFO] Search completed successfully for query: 'rammstein'
2025-06-12 04:15:23 [INFO] Added track download task 4fed13de-5827-44d5-a69e-42c3d1557f80 to Celery queue.
2025-06-12 04:15:26 [INFO] Added/Updated history for task_id: 15fc7eda-558a-435d-a9c7-cbef6aa33546, status: CANCELLED
2025-06-12 04:15:26 [INFO] Task 15fc7eda-558a-435d-a9c7-cbef6aa33546 cancelled by user. Data scheduled for deletion in 30s.
```

**Version**
2.5.0

**Comment by Xoconoch** [comment]
Fixed in 3.0

**Comment by saschabrockel** [comment]
Sorry, but that isn't fixed. I don't know why, but it's still the same.

**Comment by eidolonjs** [comment]
Having exactly the same error with same log entries.  Item queues, sometimes shows initializing, but never downloads.

**Comment by saschabrockel** [comment]
@eidolonjs are you also using unraid? Trying to find the reason... I even reinstalled and have the same. After an OS restart it works instantly for a while and at some time just stops.

**Comment by eidolonjs** [comment]
> [@eidolonjs](https://github.com/eidolonjs) are you also using unraid? Trying to find the reason... I even reinstalled and have the same. After an OS restart it works instantly for a while and at some time just stops.

Affirm, using Unraid with the CA template.  I will try running the docker compose directly next.

**Comment by saschabrockel** [comment]
> > [@eidolonjs](https://github.com/eidolonjs) are you also using unraid? Trying to find the reason... I even reinstalled and have the same. After an OS restart it works instantly for a while and at some time just stops.
> 
> Affirm, using Unraid with the CA template. I will try running the docker compose directly next.

Interesting. I created my own template though. But I have no idea what should be the reason / difference. I tested it once in an Ubuntu VM and it worked but I also tested it for a short time.

**Comment by eidolonjs** [comment]
Tried as a docker compose stack on Unraid, works fine.  Just doesn't work with the CA template.  Only thing I can think is that it has something to do with all those python pickle errors in the logs.  Don't see those in the compose stack.

I'm not smart enough to understand exactly what those errors mean.

**Comment by saschabrockel** [comment]
I could probably fix it because after the restart now it instantly worked and started to download.
I forgot about the error and deep-dived a bit. `Redis` is the problem. Do you also use one Redis instance/container for multiple other containers? I changed the `REDIS_DB` to `3`, `REDIS_URL` to `redis://redis:6379/3` and `REDIS_BACKEND` to `redis://redis:6379/3`

**Comment by Xoconoch** [comment]
Weird, it should’ve automatically detected an already populated DB and changed automatically

**Comment by saschabrockel** [comment]
Perhaps it's because I'm using the old environment variables, as I mentioned. I saw your new `.env` example but mine look like this:

<img width="1185" height="637" alt="Image" src="https://github.com/user-attachments/assets/25a2f0d7-552a-46fe-bed9-cb8e2c4ae2dc" />

**Comment by McJoppy** [comment]
> I could probably fix it because after the restart now it instantly worked and started to download. I forgot about the error and deep-dived a bit. `Redis` is the problem. Do you also use one Redis instance/container for multiple other containers? I changed the `REDIS_DB` to `3`, `REDIS_URL` to `redis://redis:6379/3` and `REDIS_BACKEND` to `redis://redis:6379/3`

Updated DB to 10, and set `REDIS_URL` and `REDIS_BACKEND` as didn't see these documented anywhere.... looks to be processing now!

Thanks
